[greeter]
background=/usr/share/backgrounds/nexusos/nexusos-prism-12.svg
theme-name=Arc-Dark
icon-theme-name=Papirus-Dark
font-name=Noto Sans 10
indicators=~host;~spacer;~clock;~spacer;~language;~session;~power
clock-format=%H:%M  •  %A, %d/%m/%Y
screensaver-timeout=60
